version: '3.8'

services:
  onp-premium:
    build: .
    container_name: onp_premium_app
    ports:
      - "8501:8501"
    restart: unless-stopped
    # Montage de volume pour persister les modèles si nécessaire
    volumes:
      - ./models:/app/models
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
